  services:
    postgres:
      image: postgres:15
      container_name: splitwise-db
      restart: always
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: splitwise
      ports:
        - '5432:5432'
      volumes:
        - postgres_data:/var/lib/postgresql/data

    app:
      build: .
      container_name: splitwise-app
      restart: always
      ports:
        - '3333:3333'
      environment:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/splitwise
        JWT_SECRET: "super-secret-key"
        PORT: 3333
      depends_on:
        - postgres
      env_file:
        - .env

  volumes:
    postgres_data:
    pgadmin-data:
